import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header"
import Footer from "./components/Footer";
import ToastProvider from "./components/ToastProvider"
import Head from 'next/head';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
       <head>
        <script
          src="//code.tidio.co/qdooksfizp0t2mpcla797raduz6rnty3.js"
          async
        ></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                <ToastProvider>

        <Header   />
        {children}
        <Footer   />
                </ToastProvider>
      </body>
    </html>
  );
}
